'use strict';

/**
 * @format
 * @flow
 */

export const CREATE_SESSION_REQUEST: string = 'CREATE_SESSION_REQUEST';
export const CREATE_SESSION_SUCCESS: string = 'CREATE_SESSION_SUCCESS';
export const CREATE_SESSION_FAILURE: string = 'CREATE_SESSION_FAILURE';
export const GET_SESSION_INFO_REQUEST: string = 'GET_SESSION_INFO_REQUEST';
export const GET_SESSION_INFO_SUCCESS: string = 'GET_SESSION_INFO_SUCCESS';
export const GET_SESSION_INFO_FAILURE: string = 'GET_SESSION_INFO_FAILURE';
export const GET_TRENDING_SESSIONS_REQUEST: string = 'GET_TRENDING_SESSIONS_REQUEST';
export const GET_TRENDING_SESSIONS_SUCCESS: string = 'GET_TRENDING_SESSIONS_SUCCESS';
export const GET_TRENDING_SESSIONS_FAILURE: string = 'GET_TRENDING_SESSIONS_FAILURE';
export const JOIN_SESSION_REQUEST: string = 'JOIN_SESSION_REQUEST';
export const JOIN_SESSION_SUCCESS: string = 'JOIN_SESSION_SUCCESS';
export const JOIN_SESSION_FAILURE: string = 'JOIN_SESSION_FAILURE';
export const LEAVE_SESSION_REQUEST: string = 'LEAVE_SESSION_REQUEST';
export const LEAVE_SESSION_SUCCESS: string = 'LEAVE_SESSION_SUCCESS';
export const LEAVE_SESSION_FAILURE: string = 'LEAVE_SESSION_FAILURE';
export const PAGINATE_TRENDING_SESSIONS_REQUEST: string = 'PAGINATE_TRENDING_SESSIONS_REQUEST';
export const PAGINATE_TRENDING_SESSIONS_SUCCESS: string = 'PAGINATE_TRENDING_SESSIONS_SUCCESS';
export const PAGINATE_TRENDING_SESSIONS_FAILURE: string = 'PAGINATE_TRENDING_SESSIONS_FAILURE';
export const RESET_SESSIONS: string = 'RESET_SESSIONS';
export const SAVE_SESSION_REQUEST: string = 'SAVE_SESSION_REQUEST';
export const SAVE_SESSION_SUCCESS: string = 'SAVE_SESSION_SUCCESS';
export const SAVE_SESSION_FAILURE: string = 'SAVE_SESSION_FAILURE';
export const STOP_SESSION_INFO_LISTENER_REQUEST: string = 'STOP_SESSION_INFO_LISTENER_REQUEST';
export const STOP_SESSION_INFO_LISTENER_SUCCESS: string = 'STOP_SESSION_INFO_LISTENER_SUCCESS';
export const STOP_SESSION_INFO_LISTENER_FAILURE: string = 'STOP_SESSION_INFO_LISTENER_FAILURE';
export const UPDATE_SESSIONS: string = 'UPDATE_SESSIONS';