'use strict';

/**
 * @format
 * @flow
 */

export const ADD_SESSIONS: string = 'ADD_SESSIONS';
export const CHANGE_NP_ROLE_REQUEST: string = 'CHANGE_ROLE_REQUEST';
export const CHANGE_NP_ROLE_SUCCESS: string = 'CHANGE_ROLE_SUCCESS';
export const CHANGE_NP_ROLE_FAILURE: string = 'CHANGE_ROLE_FAILURE';
export const CHANGE_SESSION_MODE_REQUEST: string = 'CHANGE_SESSION_MODE_REQUEST';
export const CHANGE_SESSION_MODE_SUCCESS: string = 'CHANGE_SESSION_MODE_SUCCESS';
export const CHANGE_SESSION_MODE_FAILURE: string = 'CHANGE_SESSION_MODE_FAILURE';
export const CREATE_SESSION_REQUEST: string = 'CREATE_SESSION_REQUEST';
export const CREATE_SESSION_SUCCESS: string = 'CREATE_SESSION_SUCCESS';
export const CREATE_SESSION_FAILURE: string = 'CREATE_SESSION_FAILURE';
export const GET_FOLLOWING_SESSIONS_REQUEST: string = 'GET_FOLLOWING_SESSIONS_REQUEST';
export const GET_FOLLOWING_SESSIONS_SUCCESS: string = 'GET_FOLLOWING_SESSIONS_SUCCESS';
export const GET_FOLLOWING_SESSIONS_FAILURE: string = 'GET_FOLLOWING_SESSIONS_FAILURE';
export const GET_NEARBY_SESSIONS_REQUEST: string = 'GET_NEARBY_SESSIONS_REQUEST';
export const GET_NEARBY_SESSIONS_SUCCESS: string = 'GET_NEARBY_SESSIONS_SUCCESS';
export const GET_NEARBY_SESSIONS_FAILURE: string = 'GET_NEARBY_SESSIONS_FAILURE';
export const GET_NP_KICKED_USERS_REQUEST: string = 'GET_NP_KICKED_USERS_REQUEST';
export const GET_NP_KICKED_USERS_SUCCESS: string = 'GET_NP_KICKED_USERS_SUCCESS';
export const GET_NP_KICKED_USERS_FAILURE: string = 'GET_NP_KICKED_USERS_FAILURE';
export const GET_NP_LISTENERS_REQUEST: string = 'GET_NP_LISTENERS_REQUEST';
export const GET_NP_LISTENERS_SUCCESS: string = 'GET_NP_LISTENERS_SUCCESS';
export const GET_NP_LISTENERS_FAILURE: string = 'GET_NP_LISTENERS_FAILURE';
export const GET_SESSION_INFO_REQUEST: string = 'GET_SESSION_INFO_REQUEST';
export const GET_SESSION_INFO_SUCCESS: string = 'GET_SESSION_INFO_SUCCESS';
export const GET_SESSION_INFO_FAILURE: string = 'GET_SESSION_INFO_FAILURE';
export const GET_TRENDING_SESSIONS_REQUEST: string = 'GET_TRENDING_SESSIONS_REQUEST';
export const GET_TRENDING_SESSIONS_SUCCESS: string = 'GET_TRENDING_SESSIONS_SUCCESS';
export const GET_TRENDING_SESSIONS_FAILURE: string = 'GET_TRENDING_SESSIONS_FAILURE';
export const JOIN_SESSION_REQUEST: string = 'JOIN_SESSION_REQUEST';
export const JOIN_SESSION_SUCCESS: string = 'JOIN_SESSION_SUCCESS';
export const JOIN_SESSION_FAILURE: string = 'JOIN_SESSION_FAILURE';
export const LEAVE_SESSION_REQUEST: string = 'LEAVE_SESSION_REQUEST';
export const LEAVE_SESSION_SUCCESS: string = 'LEAVE_SESSION_SUCCESS';
export const LEAVE_SESSION_FAILURE: string = 'LEAVE_SESSION_FAILURE';
export const PAGINATE_FOLLOWING_SESSIONS_REQUEST: string = 'PAGINATE_FOLLOWING_SESSIONS_REQUEST';
export const PAGINATE_FOLLOWING_SESSIONS_SUCCESS: string = 'PAGINATE_FOLLOWING_SESSIONS_SUCCESS';
export const PAGINATE_FOLLOWING_SESSIONS_FAILURE: string = 'PAGINATE_FOLLOWING_SESSIONS_FAILURE';
export const PAGINATE_NEARBY_SESSIONS_REQUEST: string = 'PAGINATE_NEARBY_SESSIONS_REQUEST';
export const PAGINATE_NEARBY_SESSIONS_SUCCESS: string = 'PAGINATE_NEARBY_SESSIONS_SUCCESS';
export const PAGINATE_NEARBY_SESSIONS_FAILURE: string = 'PAGINATE_NEARBY_SESSIONS_FAILURE';
export const PAGINATE_TRENDING_SESSIONS_REQUEST: string = 'PAGINATE_TRENDING_SESSIONS_REQUEST';
export const PAGINATE_TRENDING_SESSIONS_SUCCESS: string = 'PAGINATE_TRENDING_SESSIONS_SUCCESS';
export const PAGINATE_TRENDING_SESSIONS_FAILURE: string = 'PAGINATE_TRENDING_SESSIONS_FAILURE';
export const REMOVE_SESSION: string = 'REMOVE_SESSION';
export const RESET_SESSIONS: string = 'RESET_SESSIONS';
export const STOP_SESSION_INFO_LISTENER_REQUEST: string = 'STOP_SESSION_INFO_LISTENER_REQUEST';
export const STOP_SESSION_INFO_LISTENER_SUCCESS: string = 'STOP_SESSION_INFO_LISTENER_SUCCESS';
export const STOP_SESSION_INFO_LISTENER_FAILURE: string = 'STOP_SESSION_INFO_LISTENER_FAILURE';
export const UPDATE_SESSIONS: string = 'UPDATE_SESSIONS';