'use strict';

/**
 * @format
 * @flow
 */

export const ADD_CONVERSATION_RECIPIENT: string = 'ADD_CONVERSATION_RECIPIENT';
export const CHECK_UNLISTENED_MUSIC_REQUEST: string = 'CHECK_UNLISTENED_MUSIC_REQUEST';
export const CHECK_UNLISTENED_MUSIC_SUCCESS: string = 'CHECK_UNLISTENED_MUSIC_SUCCESS';
export const CHECK_UNLISTENED_MUSIC_FAILURE: string = 'CHECK_UNLISTENED_MUSIC_FAILURE';
export const CHECK_UNREAD_CONVERSATION_REQUEST: string = 'CHECK_UNREAD_CONVERSATION_REQUEST';
export const CHECK_UNREAD_CONVERSATION_SUCCESS: string = 'CHECK_UNREAD_CONVERSATION_SUCCESS';
export const CHECK_UNREAD_CONVERSATION_FAILURE: string = 'CHECK_UNREAD_CONVERSATION_FAILURE';
export const CLEAR_CONVERSATION_HISTORY_REQUEST: string = 'CLEAR_CONVERSATION_HISTORY_REQUEST';
export const CLEAR_CONVERSATION_HISTORY_SUCCESS: string = 'CLEAR_CONVERSATION_HISTORY_SUCCESS';
export const CLEAR_CONVERSATION_HISTORY_FAILURE: string = 'CLEAR_CONVERSATION_HISTORY_FAILURE';
export const CLEAR_NEW_CONVERSATION: string = 'CLEAR_NEW_CONVERSATION';
export const EXPAND_SHARED_MUSIC_REQUEST: string = 'EXPAND_SHARED_MUSIC_REQUEST';
export const EXPAND_SHARED_MUSIC_SUCCESS: string = 'EXPAND_SHARED_MUSIC_SUCCESS';
export const EXPAND_SHARED_MUSIC_FAILURE: string = 'EXPAND_SHARED_MUSIC_FAILURE';
export const GET_MESSAGES_REQUEST: string = 'GET_MESSAGES_REQUEST';
export const GET_MESSAGES_SUCCESS: string = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAILURE: string = 'GET_MESSAGES_FAILURE';
export const REMOVE_CONVERSATION_RECIPIENT: string = 'REMOVE_CONVERSATION_RECIPIENT';
export const SEND_CONVERSATION_MESSAGE_REQUEST: string = 'SEND_CONVERSATION_MESSAGE_REQUEST';
export const SEND_CONVERSATION_MESSAGE_SUCCESS: string = 'SEND_CONVERSATION_MESSAGE_SUCCESS';
export const SEND_CONVERSATION_MESSAGE_FAILURE: string = 'SEND_CONVERSATION_MESSAGE_FAILURE';
export const SEND_NEW_CONVERSATION_REQUEST: string = 'SEND_NEW_CONVERSATION_REQUEST';
export const SEND_NEW_CONVERSATION_SUCCESS: string = 'SEND_NEW_CONVERSATION_SUCCESS';
export const SEND_NEW_CONVERSATION_FAILURE: string = 'SEND_NEW_CONVERSATION_FAILURE';
export const SET_CONVERSATION_MESSAGE: string = 'SET_CONVERSATION_MESSAGE';
export const SET_NEW_CONVERSATION_MESSAGE: string = 'SET_NEW_CONVERSATION_MESSAGE';
export const TOGGLE_MUTE_CONVERSATION_REQUEST: string = 'TOGGLE_MUTE_CONVERSATION_REQUEST';
export const TOGGLE_MUTE_CONVERSATION_SUCCESS: string = 'TOGGLE_MUTE_CONVERSATION_SUCCESS';
export const TOGGLE_MUTE_CONVERSATION_FAILURE: string = 'TOGGLE_MUTE_CONVERSATION_FAILURE';