// flow-typed signature: a1dea8779d2378494a309125dc05d0d8
// flow-typed version: <<STUB>>/babel-plugin-rewrite-require_v1.14.5/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-rewrite-require'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-rewrite-require' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-plugin-rewrite-require/index' {
  declare module.exports: $Exports<'babel-plugin-rewrite-require'>;
}
declare module 'babel-plugin-rewrite-require/index.js' {
  declare module.exports: $Exports<'babel-plugin-rewrite-require'>;
}
