// flow-typed signature: 99816e15a116714df9912eab197ed3b8
// flow-typed version: <<STUB>>/geofirestore_v3.2.3/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'geofirestore'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'geofirestore' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'geofirestore/dist/geofirestore' {
  declare module.exports: any;
}

declare module 'geofirestore/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'geofirestore/dist/index.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'geofirestore/dist/geofirestore.js' {
  declare module.exports: $Exports<'geofirestore/dist/geofirestore'>;
}
declare module 'geofirestore/dist/index.cjs.js' {
  declare module.exports: $Exports<'geofirestore/dist/index.cjs'>;
}
declare module 'geofirestore/dist/index.esm.js' {
  declare module.exports: $Exports<'geofirestore/dist/index.esm'>;
}
