// flow-typed signature: 9afe303e755084bbf23db84a7ba5c81c
// flow-typed version: <<STUB>>/react-native-search-box_v0.0.19/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-search-box'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-search-box' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-search-box/index' {
  declare module.exports: $Exports<'react-native-search-box'>;
}
declare module 'react-native-search-box/index.js' {
  declare module.exports: $Exports<'react-native-search-box'>;
}
