// flow-typed signature: 7c184c737658ad0c0f91bc15f196c99a
// flow-typed version: <<STUB>>/react-native-events_v1.0.14/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-events'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-events' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-events/index' {
  declare module.exports: $Exports<'react-native-events'>;
}
declare module 'react-native-events/index.js' {
  declare module.exports: $Exports<'react-native-events'>;
}
