// flow-typed signature: f1a088cd769d30a1d463c7cf59cd28aa
// flow-typed version: <<STUB>>/react-native-slider_v0.11.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-slider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-slider' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-slider/lib/Slider' {
  declare module.exports: any;
}

declare module 'react-native-slider/src/Slider' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-slider/lib/Slider.js' {
  declare module.exports: $Exports<'react-native-slider/lib/Slider'>;
}
declare module 'react-native-slider/src/Slider.js' {
  declare module.exports: $Exports<'react-native-slider/src/Slider'>;
}
