// flow-typed signature: 42684bef9d2ba9a348a1066b9b88405b
// flow-typed version: <<STUB>>/react-native-modal_v9.0.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-modal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-modal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-modal/src/index' {
  declare module.exports: any;
}

declare module 'react-native-modal/src/index.style' {
  declare module.exports: any;
}

declare module 'react-native-modal/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-modal/src/index.js' {
  declare module.exports: $Exports<'react-native-modal/src/index'>;
}
declare module 'react-native-modal/src/index.style.js' {
  declare module.exports: $Exports<'react-native-modal/src/index.style'>;
}
declare module 'react-native-modal/src/utils.js' {
  declare module.exports: $Exports<'react-native-modal/src/utils'>;
}
