// flow-typed signature: ed79f4cfd9a3843438791aa5b39fe094
// flow-typed version: <<STUB>>/react-native-interactable_v0.1.10/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-interactable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-interactable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-interactable/index.android' {
  declare module.exports: any;
}

declare module 'react-native-interactable/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-interactable/lib/index' {
  declare module.exports: any;
}

declare module 'react-native-interactable/lib/src/InteractableView' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-interactable/index.android.js' {
  declare module.exports: $Exports<'react-native-interactable/index.android'>;
}
declare module 'react-native-interactable/index.ios.js' {
  declare module.exports: $Exports<'react-native-interactable/index.ios'>;
}
declare module 'react-native-interactable/lib/index.js' {
  declare module.exports: $Exports<'react-native-interactable/lib/index'>;
}
declare module 'react-native-interactable/lib/src/InteractableView.js' {
  declare module.exports: $Exports<'react-native-interactable/lib/src/InteractableView'>;
}
