// flow-typed signature: d6f1058e78c786726780f15667a4206f
// flow-typed version: <<STUB>>/react-native-image-crop-picker_v0.23.1/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-image-crop-picker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-image-crop-picker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-image-crop-picker/index' {
  declare module.exports: $Exports<'react-native-image-crop-picker'>;
}
declare module 'react-native-image-crop-picker/index.js' {
  declare module.exports: $Exports<'react-native-image-crop-picker'>;
}
