// flow-typed signature: 2591c66cbb03b2a8b5cb9d45c535f234
// flow-typed version: <<STUB>>/react-native-render-html_v4.1.2/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-render-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-render-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-render-html/src/HTML' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/HTMLDefaultStyles' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/HTMLImage' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/HTMLRenderers' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/HTMLStyles' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/HTMLUtils' {
  declare module.exports: any;
}

declare module 'react-native-render-html/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-render-html/index' {
  declare module.exports: $Exports<'react-native-render-html'>;
}
declare module 'react-native-render-html/index.js' {
  declare module.exports: $Exports<'react-native-render-html'>;
}
declare module 'react-native-render-html/src/HTML.js' {
  declare module.exports: $Exports<'react-native-render-html/src/HTML'>;
}
declare module 'react-native-render-html/src/HTMLDefaultStyles.js' {
  declare module.exports: $Exports<'react-native-render-html/src/HTMLDefaultStyles'>;
}
declare module 'react-native-render-html/src/HTMLImage.js' {
  declare module.exports: $Exports<'react-native-render-html/src/HTMLImage'>;
}
declare module 'react-native-render-html/src/HTMLRenderers.js' {
  declare module.exports: $Exports<'react-native-render-html/src/HTMLRenderers'>;
}
declare module 'react-native-render-html/src/HTMLStyles.js' {
  declare module.exports: $Exports<'react-native-render-html/src/HTMLStyles'>;
}
declare module 'react-native-render-html/src/HTMLUtils.js' {
  declare module.exports: $Exports<'react-native-render-html/src/HTMLUtils'>;
}
declare module 'react-native-render-html/src/index.js' {
  declare module.exports: $Exports<'react-native-render-html/src/index'>;
}
