// flow-typed signature: 1e48e5a5a7bb8b53aba45b7d12ddeda1
// flow-typed version: <<STUB>>/react-native-router-flux_v4.0.6/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-router-flux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-router-flux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-router-flux/__tests__/scenes.test' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/babel.config' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/expo/__tests__/App-test' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/expo/App' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/expo/components/__tests__/StyledText-test' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/expo/components/DrawerContent' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/expo/components/MenuIcon' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/expo/components/StyledText' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/expo/components/TabBarIcon' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/expo/constants/Colors' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/expo/constants/Layout' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/expo/navigation/AppNavigator' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/expo/screens/HomeScreen' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/expo/screens/LinksScreen' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/expo/screens/SettingsScreen' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/react-native/babel.config' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/react-native/components/CustomNavBar' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/react-native/components/CustomNavBar2' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/react-native/components/CustomNavBarView' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/react-native/components/drawer/DrawerContent' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/react-native/components/EchoView' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/react-native/components/Error' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/react-native/components/Home' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/react-native/components/Launch' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/react-native/components/lightbox/BaseLightbox' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/react-native/components/lightbox/DemoLightbox' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/react-native/components/Login' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/react-native/components/Login2' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/react-native/components/Login3' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/react-native/components/MessageBar' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/react-native/components/modal/BaseModal' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/react-native/components/modal/ErrorModal' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/react-native/components/Register' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/react-native/components/TabIcon' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/react-native/components/TabView' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/react-native/Example' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/react-native/index.android' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/react-native/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/react-native/test/setup' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/redux/babel.config' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/redux/index.android' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/redux/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/redux/src/a-reducer' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/redux/src/app' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/redux/src/home' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/examples/redux/src/page' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/packages/react-native-router-flux-cli/index' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/ActionConst' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/createStackNavigatorHOC' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/createTabNavigatorHOC' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Drawer' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/index' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/LegacyTabs' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Lightbox' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/LightboxRenderer' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Modal' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/NavBar' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/navigationStore' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Overlay' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/OverlayRenderer' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/pathParser' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Reducer' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Router' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Scene' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Stack' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/State' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Tabs' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/src/Util' {
  declare module.exports: any;
}

declare module 'react-native-router-flux/test/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-router-flux/__tests__/scenes.test.js' {
  declare module.exports: $Exports<'react-native-router-flux/__tests__/scenes.test'>;
}
declare module 'react-native-router-flux/babel.config.js' {
  declare module.exports: $Exports<'react-native-router-flux/babel.config'>;
}
declare module 'react-native-router-flux/examples/expo/__tests__/App-test.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/expo/__tests__/App-test'>;
}
declare module 'react-native-router-flux/examples/expo/App.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/expo/App'>;
}
declare module 'react-native-router-flux/examples/expo/components/__tests__/StyledText-test.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/expo/components/__tests__/StyledText-test'>;
}
declare module 'react-native-router-flux/examples/expo/components/DrawerContent.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/expo/components/DrawerContent'>;
}
declare module 'react-native-router-flux/examples/expo/components/MenuIcon.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/expo/components/MenuIcon'>;
}
declare module 'react-native-router-flux/examples/expo/components/StyledText.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/expo/components/StyledText'>;
}
declare module 'react-native-router-flux/examples/expo/components/TabBarIcon.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/expo/components/TabBarIcon'>;
}
declare module 'react-native-router-flux/examples/expo/constants/Colors.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/expo/constants/Colors'>;
}
declare module 'react-native-router-flux/examples/expo/constants/Layout.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/expo/constants/Layout'>;
}
declare module 'react-native-router-flux/examples/expo/navigation/AppNavigator.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/expo/navigation/AppNavigator'>;
}
declare module 'react-native-router-flux/examples/expo/screens/HomeScreen.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/expo/screens/HomeScreen'>;
}
declare module 'react-native-router-flux/examples/expo/screens/LinksScreen.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/expo/screens/LinksScreen'>;
}
declare module 'react-native-router-flux/examples/expo/screens/SettingsScreen.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/expo/screens/SettingsScreen'>;
}
declare module 'react-native-router-flux/examples/react-native/babel.config.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/react-native/babel.config'>;
}
declare module 'react-native-router-flux/examples/react-native/components/CustomNavBar.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/react-native/components/CustomNavBar'>;
}
declare module 'react-native-router-flux/examples/react-native/components/CustomNavBar2.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/react-native/components/CustomNavBar2'>;
}
declare module 'react-native-router-flux/examples/react-native/components/CustomNavBarView.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/react-native/components/CustomNavBarView'>;
}
declare module 'react-native-router-flux/examples/react-native/components/drawer/DrawerContent.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/react-native/components/drawer/DrawerContent'>;
}
declare module 'react-native-router-flux/examples/react-native/components/EchoView.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/react-native/components/EchoView'>;
}
declare module 'react-native-router-flux/examples/react-native/components/Error.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/react-native/components/Error'>;
}
declare module 'react-native-router-flux/examples/react-native/components/Home.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/react-native/components/Home'>;
}
declare module 'react-native-router-flux/examples/react-native/components/Launch.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/react-native/components/Launch'>;
}
declare module 'react-native-router-flux/examples/react-native/components/lightbox/BaseLightbox.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/react-native/components/lightbox/BaseLightbox'>;
}
declare module 'react-native-router-flux/examples/react-native/components/lightbox/DemoLightbox.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/react-native/components/lightbox/DemoLightbox'>;
}
declare module 'react-native-router-flux/examples/react-native/components/Login.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/react-native/components/Login'>;
}
declare module 'react-native-router-flux/examples/react-native/components/Login2.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/react-native/components/Login2'>;
}
declare module 'react-native-router-flux/examples/react-native/components/Login3.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/react-native/components/Login3'>;
}
declare module 'react-native-router-flux/examples/react-native/components/MessageBar.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/react-native/components/MessageBar'>;
}
declare module 'react-native-router-flux/examples/react-native/components/modal/BaseModal.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/react-native/components/modal/BaseModal'>;
}
declare module 'react-native-router-flux/examples/react-native/components/modal/ErrorModal.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/react-native/components/modal/ErrorModal'>;
}
declare module 'react-native-router-flux/examples/react-native/components/Register.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/react-native/components/Register'>;
}
declare module 'react-native-router-flux/examples/react-native/components/TabIcon.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/react-native/components/TabIcon'>;
}
declare module 'react-native-router-flux/examples/react-native/components/TabView.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/react-native/components/TabView'>;
}
declare module 'react-native-router-flux/examples/react-native/Example.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/react-native/Example'>;
}
declare module 'react-native-router-flux/examples/react-native/index.android.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/react-native/index.android'>;
}
declare module 'react-native-router-flux/examples/react-native/index.ios.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/react-native/index.ios'>;
}
declare module 'react-native-router-flux/examples/react-native/test/setup.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/react-native/test/setup'>;
}
declare module 'react-native-router-flux/examples/redux/babel.config.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/redux/babel.config'>;
}
declare module 'react-native-router-flux/examples/redux/index.android.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/redux/index.android'>;
}
declare module 'react-native-router-flux/examples/redux/index.ios.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/redux/index.ios'>;
}
declare module 'react-native-router-flux/examples/redux/src/a-reducer.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/redux/src/a-reducer'>;
}
declare module 'react-native-router-flux/examples/redux/src/app.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/redux/src/app'>;
}
declare module 'react-native-router-flux/examples/redux/src/home.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/redux/src/home'>;
}
declare module 'react-native-router-flux/examples/redux/src/page.js' {
  declare module.exports: $Exports<'react-native-router-flux/examples/redux/src/page'>;
}
declare module 'react-native-router-flux/packages/react-native-router-flux-cli/index.js' {
  declare module.exports: $Exports<'react-native-router-flux/packages/react-native-router-flux-cli/index'>;
}
declare module 'react-native-router-flux/src/ActionConst.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/ActionConst'>;
}
declare module 'react-native-router-flux/src/createStackNavigatorHOC.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/createStackNavigatorHOC'>;
}
declare module 'react-native-router-flux/src/createTabNavigatorHOC.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/createTabNavigatorHOC'>;
}
declare module 'react-native-router-flux/src/Drawer.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Drawer'>;
}
declare module 'react-native-router-flux/src/index.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/index'>;
}
declare module 'react-native-router-flux/src/LegacyTabs.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/LegacyTabs'>;
}
declare module 'react-native-router-flux/src/Lightbox.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Lightbox'>;
}
declare module 'react-native-router-flux/src/LightboxRenderer.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/LightboxRenderer'>;
}
declare module 'react-native-router-flux/src/Modal.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Modal'>;
}
declare module 'react-native-router-flux/src/NavBar.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/NavBar'>;
}
declare module 'react-native-router-flux/src/navigationStore.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/navigationStore'>;
}
declare module 'react-native-router-flux/src/Overlay.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Overlay'>;
}
declare module 'react-native-router-flux/src/OverlayRenderer.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/OverlayRenderer'>;
}
declare module 'react-native-router-flux/src/pathParser.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/pathParser'>;
}
declare module 'react-native-router-flux/src/Reducer.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Reducer'>;
}
declare module 'react-native-router-flux/src/Router.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Router'>;
}
declare module 'react-native-router-flux/src/Scene.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Scene'>;
}
declare module 'react-native-router-flux/src/Stack.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Stack'>;
}
declare module 'react-native-router-flux/src/State.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/State'>;
}
declare module 'react-native-router-flux/src/Tabs.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Tabs'>;
}
declare module 'react-native-router-flux/src/Util.js' {
  declare module.exports: $Exports<'react-native-router-flux/src/Util'>;
}
declare module 'react-native-router-flux/test/setup.js' {
  declare module.exports: $Exports<'react-native-router-flux/test/setup'>;
}
