// flow-typed signature: a72e6decb003aa596e244438d96eb46b
// flow-typed version: <<STUB>>/rn-placeholder_v1.3.3/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rn-placeholder'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rn-placeholder' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rn-placeholder/setup/test.setup' {
  declare module.exports: any;
}

declare module 'rn-placeholder/src/animation/animations' {
  declare module.exports: any;
}

declare module 'rn-placeholder/src/animation/fade' {
  declare module.exports: any;
}

declare module 'rn-placeholder/src/animation/shine' {
  declare module.exports: any;
}

declare module 'rn-placeholder/src/box/box.style' {
  declare module.exports: any;
}

declare module 'rn-placeholder/src/components' {
  declare module.exports: any;
}

declare module 'rn-placeholder/src/imageContent/imageContent' {
  declare module.exports: any;
}

declare module 'rn-placeholder/src/line/line.style' {
  declare module.exports: any;
}

declare module 'rn-placeholder/src/media/media.style' {
  declare module.exports: any;
}

declare module 'rn-placeholder/src/multiWords/multiWords' {
  declare module.exports: any;
}

declare module 'rn-placeholder/src/paragraph/paragraph' {
  declare module.exports: any;
}

declare module 'rn-placeholder/src/placeholder' {
  declare module.exports: any;
}

declare module 'rn-placeholder/src/placeholderContainer' {
  declare module.exports: any;
}

declare module 'rn-placeholder/src/placeholderStylify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rn-placeholder/index' {
  declare module.exports: $Exports<'rn-placeholder'>;
}
declare module 'rn-placeholder/index.js' {
  declare module.exports: $Exports<'rn-placeholder'>;
}
declare module 'rn-placeholder/setup/test.setup.js' {
  declare module.exports: $Exports<'rn-placeholder/setup/test.setup'>;
}
declare module 'rn-placeholder/src/animation/animations.js' {
  declare module.exports: $Exports<'rn-placeholder/src/animation/animations'>;
}
declare module 'rn-placeholder/src/animation/fade.js' {
  declare module.exports: $Exports<'rn-placeholder/src/animation/fade'>;
}
declare module 'rn-placeholder/src/animation/shine.js' {
  declare module.exports: $Exports<'rn-placeholder/src/animation/shine'>;
}
declare module 'rn-placeholder/src/box/box.style.js' {
  declare module.exports: $Exports<'rn-placeholder/src/box/box.style'>;
}
declare module 'rn-placeholder/src/components.js' {
  declare module.exports: $Exports<'rn-placeholder/src/components'>;
}
declare module 'rn-placeholder/src/imageContent/imageContent.js' {
  declare module.exports: $Exports<'rn-placeholder/src/imageContent/imageContent'>;
}
declare module 'rn-placeholder/src/line/line.style.js' {
  declare module.exports: $Exports<'rn-placeholder/src/line/line.style'>;
}
declare module 'rn-placeholder/src/media/media.style.js' {
  declare module.exports: $Exports<'rn-placeholder/src/media/media.style'>;
}
declare module 'rn-placeholder/src/multiWords/multiWords.js' {
  declare module.exports: $Exports<'rn-placeholder/src/multiWords/multiWords'>;
}
declare module 'rn-placeholder/src/paragraph/paragraph.js' {
  declare module.exports: $Exports<'rn-placeholder/src/paragraph/paragraph'>;
}
declare module 'rn-placeholder/src/placeholder.js' {
  declare module.exports: $Exports<'rn-placeholder/src/placeholder'>;
}
declare module 'rn-placeholder/src/placeholderContainer.js' {
  declare module.exports: $Exports<'rn-placeholder/src/placeholderContainer'>;
}
declare module 'rn-placeholder/src/placeholderStylify.js' {
  declare module.exports: $Exports<'rn-placeholder/src/placeholderStylify'>;
}
