// flow-typed signature: 14661bb8587b6cce68abd2906583ae41
// flow-typed version: <<STUB>>/rn-spotify-sdk_v1.2.6/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rn-spotify-sdk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rn-spotify-sdk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rn-spotify-sdk/android/external/SpotifyAuthSDK/docs/script' {
  declare module.exports: any;
}

declare module 'rn-spotify-sdk/android/external/SpotifyStreamingSDK/docs/player/script' {
  declare module.exports: any;
}

declare module 'rn-spotify-sdk/example-server/index' {
  declare module.exports: any;
}

declare module 'rn-spotify-sdk/example/__tests__/App' {
  declare module.exports: any;
}

declare module 'rn-spotify-sdk/example/App' {
  declare module.exports: any;
}

declare module 'rn-spotify-sdk/example/babel.config' {
  declare module.exports: any;
}

declare module 'rn-spotify-sdk/example/index' {
  declare module.exports: any;
}

declare module 'rn-spotify-sdk/example/InitialScreen' {
  declare module.exports: any;
}

declare module 'rn-spotify-sdk/example/PlayerScreen' {
  declare module.exports: any;
}

declare module 'rn-spotify-sdk/src/Queue' {
  declare module.exports: any;
}

declare module 'rn-spotify-sdk/src/Spotify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rn-spotify-sdk/android/external/SpotifyAuthSDK/docs/script.js' {
  declare module.exports: $Exports<'rn-spotify-sdk/android/external/SpotifyAuthSDK/docs/script'>;
}
declare module 'rn-spotify-sdk/android/external/SpotifyStreamingSDK/docs/player/script.js' {
  declare module.exports: $Exports<'rn-spotify-sdk/android/external/SpotifyStreamingSDK/docs/player/script'>;
}
declare module 'rn-spotify-sdk/example-server/index.js' {
  declare module.exports: $Exports<'rn-spotify-sdk/example-server/index'>;
}
declare module 'rn-spotify-sdk/example/__tests__/App.js' {
  declare module.exports: $Exports<'rn-spotify-sdk/example/__tests__/App'>;
}
declare module 'rn-spotify-sdk/example/App.js' {
  declare module.exports: $Exports<'rn-spotify-sdk/example/App'>;
}
declare module 'rn-spotify-sdk/example/babel.config.js' {
  declare module.exports: $Exports<'rn-spotify-sdk/example/babel.config'>;
}
declare module 'rn-spotify-sdk/example/index.js' {
  declare module.exports: $Exports<'rn-spotify-sdk/example/index'>;
}
declare module 'rn-spotify-sdk/example/InitialScreen.js' {
  declare module.exports: $Exports<'rn-spotify-sdk/example/InitialScreen'>;
}
declare module 'rn-spotify-sdk/example/PlayerScreen.js' {
  declare module.exports: $Exports<'rn-spotify-sdk/example/PlayerScreen'>;
}
declare module 'rn-spotify-sdk/index' {
  declare module.exports: $Exports<'rn-spotify-sdk'>;
}
declare module 'rn-spotify-sdk/index.js' {
  declare module.exports: $Exports<'rn-spotify-sdk'>;
}
declare module 'rn-spotify-sdk/src/Queue.js' {
  declare module.exports: $Exports<'rn-spotify-sdk/src/Queue'>;
}
declare module 'rn-spotify-sdk/src/Spotify.js' {
  declare module.exports: $Exports<'rn-spotify-sdk/src/Spotify'>;
}
