// flow-typed signature: a32f09fe442c12aa933731b5720565dd
// flow-typed version: <<STUB>>/unsplash-js_v5.0.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unsplash-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'unsplash-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'unsplash-js/dist/unsplash' {
  declare module.exports: any;
}

declare module 'unsplash-js/dist/unsplash.min' {
  declare module.exports: any;
}

declare module 'unsplash-js/examples/node/app' {
  declare module.exports: any;
}

declare module 'unsplash-js/examples/node/config/server' {
  declare module.exports: any;
}

declare module 'unsplash-js/examples/node/index' {
  declare module.exports: any;
}

declare module 'unsplash-js/examples/umd/public/main' {
  declare module.exports: any;
}

declare module 'unsplash-js/examples/umd/server' {
  declare module.exports: any;
}

declare module 'unsplash-js/examples/webpack/index' {
  declare module.exports: any;
}

declare module 'unsplash-js/examples/webpack/main' {
  declare module.exports: any;
}

declare module 'unsplash-js/examples/webpack/server' {
  declare module.exports: any;
}

declare module 'unsplash-js/examples/webpack/webpack.config' {
  declare module.exports: any;
}

declare module 'unsplash-js/karma.conf' {
  declare module.exports: any;
}

declare module 'unsplash-js/lib/constants/index' {
  declare module.exports: any;
}

declare module 'unsplash-js/lib/methods/auth' {
  declare module.exports: any;
}

declare module 'unsplash-js/lib/methods/categories' {
  declare module.exports: any;
}

declare module 'unsplash-js/lib/methods/collections' {
  declare module.exports: any;
}

declare module 'unsplash-js/lib/methods/currentUser' {
  declare module.exports: any;
}

declare module 'unsplash-js/lib/methods/photos' {
  declare module.exports: any;
}

declare module 'unsplash-js/lib/methods/search' {
  declare module.exports: any;
}

declare module 'unsplash-js/lib/methods/stats' {
  declare module.exports: any;
}

declare module 'unsplash-js/lib/methods/users' {
  declare module.exports: any;
}

declare module 'unsplash-js/lib/unsplash' {
  declare module.exports: any;
}

declare module 'unsplash-js/lib/utils/index' {
  declare module.exports: any;
}

declare module 'unsplash-js/native' {
  declare module.exports: any;
}

declare module 'unsplash-js/src/constants/index' {
  declare module.exports: any;
}

declare module 'unsplash-js/src/methods/auth' {
  declare module.exports: any;
}

declare module 'unsplash-js/src/methods/categories' {
  declare module.exports: any;
}

declare module 'unsplash-js/src/methods/collections' {
  declare module.exports: any;
}

declare module 'unsplash-js/src/methods/currentUser' {
  declare module.exports: any;
}

declare module 'unsplash-js/src/methods/photos' {
  declare module.exports: any;
}

declare module 'unsplash-js/src/methods/search' {
  declare module.exports: any;
}

declare module 'unsplash-js/src/methods/stats' {
  declare module.exports: any;
}

declare module 'unsplash-js/src/methods/users' {
  declare module.exports: any;
}

declare module 'unsplash-js/src/unsplash' {
  declare module.exports: any;
}

declare module 'unsplash-js/src/utils/index' {
  declare module.exports: any;
}

declare module 'unsplash-js/tests.webpack' {
  declare module.exports: any;
}

declare module 'unsplash-js/webpack.config.base' {
  declare module.exports: any;
}

declare module 'unsplash-js/webpack.config.development' {
  declare module.exports: any;
}

declare module 'unsplash-js/webpack.config.production' {
  declare module.exports: any;
}

// Filename aliases
declare module 'unsplash-js/dist/unsplash.js' {
  declare module.exports: $Exports<'unsplash-js/dist/unsplash'>;
}
declare module 'unsplash-js/dist/unsplash.min.js' {
  declare module.exports: $Exports<'unsplash-js/dist/unsplash.min'>;
}
declare module 'unsplash-js/examples/node/app.js' {
  declare module.exports: $Exports<'unsplash-js/examples/node/app'>;
}
declare module 'unsplash-js/examples/node/config/server.js' {
  declare module.exports: $Exports<'unsplash-js/examples/node/config/server'>;
}
declare module 'unsplash-js/examples/node/index.js' {
  declare module.exports: $Exports<'unsplash-js/examples/node/index'>;
}
declare module 'unsplash-js/examples/umd/public/main.js' {
  declare module.exports: $Exports<'unsplash-js/examples/umd/public/main'>;
}
declare module 'unsplash-js/examples/umd/server.js' {
  declare module.exports: $Exports<'unsplash-js/examples/umd/server'>;
}
declare module 'unsplash-js/examples/webpack/index.js' {
  declare module.exports: $Exports<'unsplash-js/examples/webpack/index'>;
}
declare module 'unsplash-js/examples/webpack/main.js' {
  declare module.exports: $Exports<'unsplash-js/examples/webpack/main'>;
}
declare module 'unsplash-js/examples/webpack/server.js' {
  declare module.exports: $Exports<'unsplash-js/examples/webpack/server'>;
}
declare module 'unsplash-js/examples/webpack/webpack.config.js' {
  declare module.exports: $Exports<'unsplash-js/examples/webpack/webpack.config'>;
}
declare module 'unsplash-js/karma.conf.js' {
  declare module.exports: $Exports<'unsplash-js/karma.conf'>;
}
declare module 'unsplash-js/lib/constants/index.js' {
  declare module.exports: $Exports<'unsplash-js/lib/constants/index'>;
}
declare module 'unsplash-js/lib/methods/auth.js' {
  declare module.exports: $Exports<'unsplash-js/lib/methods/auth'>;
}
declare module 'unsplash-js/lib/methods/categories.js' {
  declare module.exports: $Exports<'unsplash-js/lib/methods/categories'>;
}
declare module 'unsplash-js/lib/methods/collections.js' {
  declare module.exports: $Exports<'unsplash-js/lib/methods/collections'>;
}
declare module 'unsplash-js/lib/methods/currentUser.js' {
  declare module.exports: $Exports<'unsplash-js/lib/methods/currentUser'>;
}
declare module 'unsplash-js/lib/methods/photos.js' {
  declare module.exports: $Exports<'unsplash-js/lib/methods/photos'>;
}
declare module 'unsplash-js/lib/methods/search.js' {
  declare module.exports: $Exports<'unsplash-js/lib/methods/search'>;
}
declare module 'unsplash-js/lib/methods/stats.js' {
  declare module.exports: $Exports<'unsplash-js/lib/methods/stats'>;
}
declare module 'unsplash-js/lib/methods/users.js' {
  declare module.exports: $Exports<'unsplash-js/lib/methods/users'>;
}
declare module 'unsplash-js/lib/unsplash.js' {
  declare module.exports: $Exports<'unsplash-js/lib/unsplash'>;
}
declare module 'unsplash-js/lib/utils/index.js' {
  declare module.exports: $Exports<'unsplash-js/lib/utils/index'>;
}
declare module 'unsplash-js/native.js' {
  declare module.exports: $Exports<'unsplash-js/native'>;
}
declare module 'unsplash-js/src/constants/index.js' {
  declare module.exports: $Exports<'unsplash-js/src/constants/index'>;
}
declare module 'unsplash-js/src/methods/auth.js' {
  declare module.exports: $Exports<'unsplash-js/src/methods/auth'>;
}
declare module 'unsplash-js/src/methods/categories.js' {
  declare module.exports: $Exports<'unsplash-js/src/methods/categories'>;
}
declare module 'unsplash-js/src/methods/collections.js' {
  declare module.exports: $Exports<'unsplash-js/src/methods/collections'>;
}
declare module 'unsplash-js/src/methods/currentUser.js' {
  declare module.exports: $Exports<'unsplash-js/src/methods/currentUser'>;
}
declare module 'unsplash-js/src/methods/photos.js' {
  declare module.exports: $Exports<'unsplash-js/src/methods/photos'>;
}
declare module 'unsplash-js/src/methods/search.js' {
  declare module.exports: $Exports<'unsplash-js/src/methods/search'>;
}
declare module 'unsplash-js/src/methods/stats.js' {
  declare module.exports: $Exports<'unsplash-js/src/methods/stats'>;
}
declare module 'unsplash-js/src/methods/users.js' {
  declare module.exports: $Exports<'unsplash-js/src/methods/users'>;
}
declare module 'unsplash-js/src/unsplash.js' {
  declare module.exports: $Exports<'unsplash-js/src/unsplash'>;
}
declare module 'unsplash-js/src/utils/index.js' {
  declare module.exports: $Exports<'unsplash-js/src/utils/index'>;
}
declare module 'unsplash-js/tests.webpack.js' {
  declare module.exports: $Exports<'unsplash-js/tests.webpack'>;
}
declare module 'unsplash-js/webpack.config.base.js' {
  declare module.exports: $Exports<'unsplash-js/webpack.config.base'>;
}
declare module 'unsplash-js/webpack.config.development.js' {
  declare module.exports: $Exports<'unsplash-js/webpack.config.development'>;
}
declare module 'unsplash-js/webpack.config.production.js' {
  declare module.exports: $Exports<'unsplash-js/webpack.config.production'>;
}
