'use strict';

/**
 * @format
 * @flow
 */

export const DELETE_QUEUE_TRACK_REQUEST: string = 'DELETE_QUEUE_TRACK_REQUEST';
export const DELETE_QUEUE_TRACK_SUCCESS: string = 'DELETE_QUEUE_TRACK_SUCCESS';
export const DELETE_QUEUE_TRACK_FAILURE: string = 'DELETE_QUEUE_TRACK_FAILURE';
export const GET_CONTEXT_QUEUE_REQUEST: string = 'GET_CONTEXT_QUEUE_REQUEST';
export const GET_CONTEXT_QUEUE_SUCCESS: string = 'GET_CONTEXT_QUEUE_SUCCESS';
export const GET_CONTEXT_QUEUE_FAILURE: string = 'GET_CONTEXT_QUEUE_FAILURE';
export const GET_USER_QUEUE_REQUEST: string = 'GET_USER_QUEUE_REQUEST';
export const GET_USER_QUEUE_SUCCESS: string = 'GET_USER_QUEUE_SUCCESS';
export const GET_USER_QUEUE_FAILURE: string = 'GET_USER_QUEUE_FAILURE';
export const QUEUE_TRACK_REQUEST: string = 'QUEUE_TRACK_REQUEST';
export const QUEUE_TRACK_SUCCESS: string = 'QUEUE_TRACK_SUCCESS';
export const QUEUE_TRACK_FAILURE: string = 'QUEUE_TRACK_FAILURE';
export const REMOVE_QUEUE_TRACK: string = 'REMOVE_QUEUE_TRACK';
export const RESET_QUEUE: string = 'RESET_QUEUE';
export const STOP_QUEUE_LISTENER_REQUEST: string = 'STOP_QUEUE_LISTENER_REQUEST';
export const STOP_QUEUE_LISTENER_SUCCESS: string = 'STOP_QUEUE_LISTENER_SUCCESS';
export const STOP_QUEUE_LISTENER_FAILURE: string = 'STOP_QUEUE_LISTENER_FAILURE';
export const TOGGLE_TRACK_LIKE_REQUEST: string = 'TOGGLE_TRACK_LIKE_REQUEST';
export const TOGGLE_TRACK_LIKE_SUCCESS: string = 'TOGGLE_TRACK_LIKE_SUCCESS';
export const TOGGLE_TRACK_LIKE_FAILURE: string = 'TOGGLE_TRACK_LIKE_FAILURE';
export const UPDATE_QUEUE: string = 'UPDATE_QUEUE';