"use strict";

/**
 * @format
 * @flow
 */

export const GET_ALBUMS_REQUEST: string = 'GET_ALBUMS_REQUEST';
export const GET_ALBUMS_SUCCESS: string = 'GET_ALBUMS_SUCCESS';
export const GET_ALBUMS_FAILURE: string = 'GET_ALBUMS_FAILURE';
export const GET_ALBUM_TOP_LISTENERS_REQUEST: string = 'GET_ALBUM_TOP_LISTENERS_REQUEST';
export const GET_ALBUM_TOP_LISTENERS_SUCCESS: string = 'GET_ALBUM_TOP_LISTENERS_SUCCESS';
export const GET_ALBUM_TOP_LISTENERS_FAILURE: string = 'GET_ALBUM_TOP_LISTENERS_FAILURE';
export const GET_ALBUM_TOP_PLAYLISTS_REQUEST: string = 'GET_ALBUM_TOP_PLAYLISTS_REQUEST';
export const GET_ALBUM_TOP_PLAYLISTS_SUCCESS: string = 'GET_ALBUM_TOP_PLAYLISTS_SUCCESS';
export const GET_ALBUM_TOP_PLAYLISTS_FAILURE: string = 'GET_ALBUM_TOP_PLAYLISTS_FAILURE';
export const GET_ALBUM_TOP_TRACKS_REQUEST: string = 'GET_ALBUM_TOP_TRACKS_REQUEST';
export const GET_ALBUM_TOP_TRACKS_SUCCESS: string = 'GET_ALBUM_TOP_TRACKS_SUCCESS';
export const GET_ALBUM_TOP_TRACKS_FAILURE: string = 'GET_ALBUM_TOP_TRACKS_FAILURE';
export const INCREMENT_ALBUM_PLAYS_REQUEST: string = 'INCREMENT_ALBUM_PLAYS_REQUEST';
export const INCREMENT_ALBUM_PLAYS_SUCCESS: string = 'INCREMENT_ALBUM_PLAYS_SUCCESS';
export const INCREMENT_ALBUM_PLAYS_FAILURE: string = 'INCREMENT_ALBUM_PLAYS_FAILURE';
export const RESET_ALBUMS: string = 'RESET_ALBUMS';
export const UPDATE_ALBUMS: string = 'UPDATE_ALBUMS';
