'use strict';

/**
 * @format
 * @flow
 */

export const AUTHORIZE_USER_REQUEST: string = 'AUTHORIZE_USER_REQUEST';
export const AUTHORIZE_USER_SUCCESS: string = 'AUTHORIZE_USER_SUCCESS';
export const AUTHORIZE_USER_FAILURE: string = 'AUTHORIZE_USER_FAILURE';
export const CHANGE_DIRECT_MESSAGE_NOTIFICATION_REQUEST: string = 'CHANGE_DIRECT_MESSAGE_NOTIFICATION_REQUEST';
export const CHANGE_DIRECT_MESSAGE_NOTIFICATION_SUCCESS: string = 'CHANGE_DIRECT_MESSAGE_NOTIFICATION_SUCCESS';
export const CHANGE_DIRECT_MESSAGE_NOTIFICATION_FAILURE: string = 'CHANGE_DIRECT_MESSAGE_NOTIFICATION_FAILURE';
export const CHANGE_GROUP_DIRECT_MESSAGE_NOTIFICATION_REQUEST: string = 'CHANGE_GROUP_DIRECT_MESSAGE_NOTIFICATION_REQUEST';
export const CHANGE_GROUP_DIRECT_MESSAGE_NOTIFICATION_SUCCESS: string = 'CHANGE_GROUP_DIRECT_MESSAGE_NOTIFICATION_SUCCESS';
export const CHANGE_GROUP_DIRECT_MESSAGE_NOTIFICATION_FAILURE: string = 'CHANGE_GROUP_DIRECT_MESSAGE_NOTIFICATION_FAILURE';
export const CHANGE_LIKE_TRACK_NOTIFICATION_REQUEST: string = 'CHANGE_LIKE_TRACK_NOTIFICATION_REQUEST';
export const CHANGE_LIKE_TRACK_NOTIFICATION_SUCCESS: string = 'CHANGE_LIKE_TRACK_NOTIFICATION_SUCCESS';
export const CHANGE_LIKE_TRACK_NOTIFICATION_FAILURE: string = 'CHANGE_LIKE_TRACK_NOTIFICATION_FAILURE';
export const CHANGE_MESSAGE_PREFERENCE_REQUEST: string = 'CHANGE_MESSAGE_PREFERENCE_REQUEST';
export const CHANGE_MESSAGE_PREFERENCE_SUCCESS: string = 'CHANGE_MESSAGE_PREFERENCE_SUCCESS';
export const CHANGE_MESSAGE_PREFERENCE_FAILURE: string = 'CHANGE_MESSAGE_PREFERENCE_FAILURE';
export const CHANGE_NEARBY_SESSION_NOTIFICATION_REQUEST: string = 'CHANGE_NEARBY_SESSION_NOTIFICATION_REQUEST';
export const CHANGE_NEARBY_SESSION_NOTIFICATION_SUCCESS: string = 'CHANGE_NEARBY_SESSION_NOTIFICATION_SUCCESS';
export const CHANGE_NEARBY_SESSION_NOTIFICATION_FAILURE: string = 'CHANGE_NEARBY_SESSION_NOTIFICATION_FAILURE';
export const CHANGE_NEW_FOLLOWER_NOTIFICATION_REQUEST: string = 'CHANGE_NEW_FOLLOWER_NOTIFICATION_REQUEST';
export const CHANGE_NEW_FOLLOWER_NOTIFICATION_SUCCESS: string = 'CHANGE_NEW_FOLLOWER_NOTIFICATION_SUCCESS';
export const CHANGE_NEW_FOLLOWER_NOTIFICATION_FAILURE: string = 'CHANGE_NEW_FOLLOWER_NOTIFICATION_FAILURE';
export const CHANGE_PLAYLIST_CHANGE_NOTIFICATION_REQUEST: string = 'CHANGE_PLAYLIST_CHANGE_NOTIFICATION_REQUEST';
export const CHANGE_PLAYLIST_CHANGE_NOTIFICATION_SUCCESS: string = 'CHANGE_PLAYLIST_CHANGE_NOTIFICATION_SUCCESS';
export const CHANGE_PLAYLIST_CHANGE_NOTIFICATION_FAILURE: string = 'CHANGE_PLAYLIST_CHANGE_NOTIFICATION_FAILURE';
export const CHANGE_PLAYLIST_JOIN_NOTIFICATION_REQUEST: string = 'CHANGE_PLAYLIST_JOIN_NOTIFICATION_REQUEST';
export const CHANGE_PLAYLIST_JOIN_NOTIFICATION_SUCCESS: string = 'CHANGE_PLAYLIST_JOIN_NOTIFICATION_SUCCESS';
export const CHANGE_PLAYLIST_JOIN_NOTIFICATION_FAILURE: string = 'CHANGE_PLAYLIST_JOIN_NOTIFICATION_FAILURE';
export const CHANGE_PLAYLIST_PREFERENCE_REQUEST: string = 'CHANGE_PLAYLIST_PREFERENCE_REQUEST';
export const CHANGE_PLAYLIST_PREFERENCE_SUCCESS: string = 'CHANGE_PLAYLIST_PREFERENCE_SUCCESS';
export const CHANGE_PLAYLIST_PREFERENCE_FAILURE: string = 'CHANGE_PLAYLIST_PREFERENCE_FAILURE';
export const CHANGE_SESSION_CHAT_NOTIFICATION_REQUEST: string = 'CHANGE_SESSION_CHAT_NOTIFICATION_REQUEST';
export const CHANGE_SESSION_CHAT_NOTIFICATION_SUCCESS: string = 'CHANGE_SESSION_CHAT_NOTIFICATION_SUCCESS';
export const CHANGE_SESSION_CHAT_NOTIFICATION_FAILURE: string = 'CHANGE_SESSION_CHAT_NOTIFICATION_FAILURE';
export const CHANGE_SESSION_PREFERENCE_REQUEST: string = 'CHANGE_SESSION_PREFERENCE_REQUEST';
export const CHANGE_SESSION_PREFERENCE_SUCCESS: string = 'CHANGE_SESSION_PREFERENCE_SUCCESS';
export const CHANGE_SESSION_PREFERENCE_FAILURE: string = 'CHANGE_SESSION_PREFERENCE_FAILURE';
export const CHANGE_SESSIONS_NOTIFICATION_REQUEST: string = 'CHANGE_SESSIONS_NOTIFICATION_REQUEST';
export const CHANGE_SESSIONS_NOTIFICATION_SUCCESS: string = 'CHANGE_SESSIONS_NOTIFICATION_SUCCESS';
export const CHANGE_SESSIONS_NOTIFICATION_FAILURE: string = 'CHANGE_SESSIONS_NOTIFICATION_FAILURE';
export const CHANGE_SOUND_EFFECTS_REQUEST: string = 'CHANGE_SOUND_EFFECTS_REQUEST';
export const CHANGE_SOUND_EFFECTS_SUCCESS: string = 'CHANGE_SOUND_EFFECTS_SUCCESS';
export const CHANGE_SOUND_EFFECTS_FAILURE: string = 'CHANGE_SOUND_EFFECTS_FAILURE';
export const CHANGE_THEME_COLOR_REQUEST: string = 'CHANGE_THEME_COLOR_REQUEST';
export const CHANGE_THEME_COLOR_SUCCESS: string = 'CHANGE_THEME_COLOR_SUCCESS';
export const CHANGE_THEME_COLOR_FAILURE: string = 'CHANGE_THEME_COLOR_FAILURE';
export const GET_USER_SETTINGS_REQUEST: string = 'GET_USER_SETTINGS_REQUEST';
export const GET_USER_SETTINGS_SUCCESS: string = 'GET_USER_SETTINGS_SUCCESS';
export const GET_USER_SETTINGS_FAILURE: string = 'GET_USER_SETTINGS_FAILURE';
export const INITIALIZE_SPOTIFY_REQUEST: string = 'INITIALIZE_SPOTIFY_REQUEST';
export const INITIALIZE_SPOTIFY_SUCCESS: string = 'INITIALIZE_SPOTIFY_SUCCESS';
export const INITIALIZE_SPOTIFY_FAILURE: string = 'INITIALIZE_SPOTIFY_FAILURE';
export const LOG_OUT_REQUEST: string = 'LOG_OUT_REQUEST';
export const LOG_OUT_SUCCESS: string = 'LOG_OUT_SUCCESS';
export const LOG_OUT_FAILURE: string = 'LOG_OUT_FAILURE';
export const RESET_SETTINGS: string = 'RESET_SETTINGS';
export const SAVE_SETTINGS_REQUEST: string = 'SAVE_SETTINGS_REQUEST';
export const SAVE_SETTINGS_SUCCESS: string = 'SAVE_SETTINGS_SUCCESS';
export const SAVE_SETTINGS_FAILURE: string = 'SAVE_SETTINGS_FAILURE';
export const UPDATE_SETTINGS: string = 'UPDATE_SETTINGS';