'use strict';

/**
 * @format
 * @flow
 */

export const AUTHORIZE_USER_REQUEST: string = 'AUTHORIZE_USER_REQUEST';
export const AUTHORIZE_USER_SUCCESS: string = 'AUTHORIZE_USER_SUCCESS';
export const AUTHORIZE_USER_FAILURE: string = 'AUTHORIZE_USER_FAILURE';
export const GET_USER_SETTINGS_REQUEST: string = 'GET_USER_SETTINGS_REQUEST';
export const GET_USER_SETTINGS_SUCCESS: string = 'GET_USER_SETTINGS_SUCCESS';
export const GET_USER_SETTINGS_FAILURE: string = 'GET_USER_SETTINGS_FAILURE';
export const INITIALIZE_SPOTIFY_REQUEST: string = 'INITIALIZE_SPOTIFY_REQUEST';
export const INITIALIZE_SPOTIFY_SUCCESS: string = 'INITIALIZE_SPOTIFY_SUCCESS';
export const INITIALIZE_SPOTIFY_FAILURE: string = 'INITIALIZE_SPOTIFY_FAILURE';
export const LOG_OUT_REQUEST: string = 'LOG_OUT_REQUEST';
export const LOG_OUT_SUCCESS: string = 'LOG_OUT_SUCCESS';
export const LOG_OUT_FAILURE: string = 'LOG_OUT_FAILURE';
export const RESET_SETTINGS: string = 'RESET_SETTINGS';
export const SAVE_SETTINGS_REQUEST: string = 'SAVE_SETTINGS_REQUEST';
export const SAVE_SETTINGS_SUCCESS: string = 'SAVE_SETTINGS_SUCCESS';
export const SAVE_SETTINGS_FAILURE: string = 'SAVE_SETTINGS_FAILURE';
export const UPDATE_SETTINGS: string = 'UPDATE_SETTINGS';