'use strict';

/**
 * @format
 * @flow
 */

export const ADD_NOTIFICATIONS: string = 'ADD_NOTIFICATIONS';
export const ADD_NOTIFICATION_USERS: string = 'ADD_NOTIFICATION_USERS';
export const ADD_NOTIFICATION_SONGS: string = 'ADD_NOTIFICATION_SONGS';
export const CHECK_NOTIFICATIONS_PAGINATION: string = 'CHECK_NOTIFICATIONS_PAGINATION';
export const GET_NOTIFICATIONS_REQUEST: string = 'GET_NOTIFICATIONS_REQUEST';
export const GET_NOTIFICATIONS_SUCCESS: string = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_FAILURE: string = 'GET_NOTIFICATIONS_FAILURE';
export const PAGINATE_NOTIFICATIONS_REQUEST: string = 'PAGINATE_NOTIFICATIONS_REQUEST';
export const PAGINATE_NOTIFICATIONS_SUCCESS: string = 'PAGINATE_NOTIFICATIONS_SUCCESS';
export const PAGINATE_NOTIFICATIONS_FAILURE: string = 'PAGINATE_NOTIFICATIONS_FAILURE';
export const TOGGLE_NEW_NOTIFICATIONS: string = 'TOGGLE_NEW_NOTIFICATIONS';