'use strict';

/**
 * @format
 * @flow
 */

export const CLEAR_RECENT_SEARCHES_REQUEST: string = 'CLEAR_RECENT_SEARCHES_REQUEST';
export const CLEAR_RECENT_SEARCHES_SUCCESS: string = 'CLEAR_RECENT_SEARCHES_SUCCESS';
export const CLEAR_RECENT_SEARCHES_FAILURE: string = 'CLEAR_RECENT_SEARCHES_FAILURE';
export const GET_NEARBY_SEARCHES_REQUEST: string = 'GET_NEARBY_SEARCHES_REQUEST';
export const GET_NEARBY_SEARCHES_SUCCESS: string = 'GET_NEARBY_SEARCHES_SUCCESS';
export const GET_NEARBY_SEARCHES_FAILURE: string = 'GET_NEARBY_SEARCHES_FAILURE';
export const GET_RECENT_SEARCHES_REQUEST: string = 'GET_RECENT_SEARCHES_REQUEST';
export const GET_RECENT_SEARCHES_SUCCESS: string = 'GET_RECENT_SEARCHES_SUCCESS';
export const GET_RECENT_SEARCHES_FAILURE: string = 'GET_RECENT_SEARCHES_FAILURE';
export const GET_TRENDING_SEARCHES_REQUEST: string = 'GET_TRENDING_SEARCHES_REQUEST';
export const GET_TRENDING_SEARCHES_SUCCESS: string = 'GET_TRENDING_SEARCHES_SUCCESS';
export const GET_TRENDING_SEARCHES_FAILURE: string = 'GET_TRENDING_SEARCHES_FAILURE';
export const RESET_SEARCH: string = 'RESET_SEARCH';
export const SEARCH_REQUEST: string = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS: string = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE: string = 'SEARCH_FAILURE';
export const UPDATE_SEARCH: string = 'UPDATE_SEARCH';
