'use strict';

/**
 * @format
 * @flow
 */

export const ADD_FEATURED_CONTENT_REQUEST: string = 'ADD_FEATURED_CONTENT_REQUEST';
export const ADD_FEATURED_CONTENT_SUCCESS: string = 'ADD_FEATURED_CONTENT_SUCCESS';
export const ADD_FEATURED_CONTENT_FAILURE: string = 'ADD_FEATURED_CONTENT_FAILURE';
export const ADD_USER_TO_GROUP_REQUEST: string = 'ADD_USER_TO_GROUP_REQUEST';
export const ADD_USER_TO_GROUP_SUCCESS: string = 'ADD_USER_TO_GROUP_SUCCESS';
export const ADD_USER_TO_GROUP_FAILURE: string = 'ADD_USER_TO_GROUP_FAILURE';
export const CHANGE_GROUP_PHOTO_REQUEST: string = 'CHANGE_GROUP_PHOTO_REQUEST';
export const CHANGE_GROUP_PHOTO_SUCCESS: string = 'CHANGE_GROUP_PHOTO_SUCCESS';
export const CHANGE_GROUP_PHOTO_FAILURE: string = 'CHANGE_GROUP_PHOTO_FAILURE';
export const CHECK_GROUP_NAME_REQUEST: string = 'CHECK_GROUP_NAME_REQUEST';
export const CHECK_GROUP_NAME_SUCCESS: string = 'CHECK_GROUP_NAME_SUCCESS';
export const CHECK_GROUP_NAME_FAILURE: string = 'CHECK_GROUP_NAME_FAILURE';
export const CLEAR_GROUP_RECENTLY_PLAYED_REQUEST: string = 'CLEAR_GROUP_RECENTLY_PLAYED_REQUEST';
export const CLEAR_GROUP_RECENTLY_PLAYED_SUCCESS: string = 'CLEAR_GROUP_RECENTLY_PLAYED_SUCCESS';
export const CLEAR_GROUP_RECENTLY_PLAYED_FAILURE: string = 'CLEAR_GROUP_RECENTLY_PLAYED_FAILURE';
export const CREATE_GROUP_REQUEST: string = 'CREATE_GROUP_REQUEST';
export const CREATE_GROUP_SUCCESS: string = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_FAILURE: string = 'CREATE_GROUP_FAILURE';
export const DELETE_GROUP_REQUEST: string = 'DELETE_GROUP_REQUEST';
export const DELETE_GROUP_SUCCESS: string = 'DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_FAILURE: string = 'DELETE_GROUP_FAILURE';
export const EDIT_GROUP: string = 'EDIT_GROUP';
export const FOLLOW_GROUP_REQUEST: string = 'FOLLOW_GROUP_REQUEST';
export const FOLLOW_GROUP_SUCCESS: string = 'FOLLOW_GROUP_SUCCESS';
export const FOLLOW_GROUP_FAILURE: string = 'FOLLOW_GROUP_FAILURE';
export const JOIN_GROUP_REQUEST: string = 'JOIN_GROUP_REQUEST';
export const JOIN_GROUP_SUCCESS: string = 'JOIN_GROUP_SUCCESS';
export const JOIN_GROUP_FAILURE: string = 'JOIN_GROUP_FAILURE';
export const REMOVE_FEATURED_CONTENT_REQUEST: string = 'REMOVE_FEATURED_CONTENT_REQUEST';
export const REMOVE_FEATURED_CONTENT_SUCCESS: string = 'REMOVE_FEATURED_CONTENT_SUCCESS';
export const REMOVE_FEATURED_CONTENT_FAILURE: string = 'REMOVE_FEATURED_CONTENT_FAILURE';
export const REMOVE_USER_FROM_GROUP_REQUEST: string = 'REMOVE_USER_FROM_GROUP_REQUEST';
export const REMOVE_USER_FROM_GROUP_SUCCESS: string = 'REMOVE_USER_FROM_GROUP_SUCCESS';
export const REMOVE_USER_FROM_GROUP_FAILURE: string = 'REMOVE_USER_FROM_GROUP_FAILURE';
export const SAVE_GROUP_REQUEST: string = 'SAVE_GROUP_REQUEST';
export const SAVE_GROUP_SUCCESS: string = 'SAVE_GROUP_SUCCESS';
export const SAVE_GROUP_FAILURE: string = 'SAVE_GROUP_FAILURE';
export const SEARCH_GROUPS_REQUEST: string = 'SEARCH_GROUPS_REQUEST';
export const SEARCH_GROUPS_SUCCESS: string = 'SEARCH_GROUPS_SUCCESS';
export const SEARCH_GROUPS_FAILURE: string = 'SEARCH_GROUPS_FAILURE';
export const SET_GROUP_BIO: string = 'SET_GROUP_BIO';
export const SET_GROUP_LOCATION: string = 'SET_GROUP_LOCATION';
export const SET_GROUP_NAME: string = 'SET_GROUP_NAME';
export const SET_GROUP_WEBSITE: string = 'SET_GROUP_WEBSITE';
export const SET_NEW_GROUP_BIO: string = 'SET_NEW_GROUP_BIO';
export const SET_NEW_GROUP_LOCATION: string = 'SET_NEW_GROUP_LOCATION';
export const SET_NEW_GROUP_NAME: string = 'SET_NEW_GROUP_NAME';
export const SET_NEW_GROUP_PERMISSIONS: string = 'SET_NEW_GROUP_PERMISSIONS';
export const SET_NEW_GROUP_WEBSITE: string = 'SET_NEW_GROUP_WEBSITE';export const SET_: string = 'SET_';
export const SET_PERMISSIONS: string = 'SET_PERMISSIONS';
export const UNFOLLOW_GROUP_REQUEST: string = 'UNFOLLOW_GROUP_REQUEST';
export const UNFOLLOW_GROUP_SUCCESS: string = 'UNFOLLOW_GROUP_SUCCESS';
export const UNFOLLOW_GROUP_FAILURE: string = 'UNFOLLOW_GROUP_FAILURE';