"use strict";

/**
 * @format
 * @flow
 */

export const ADD_RECENT_TRACK_REQUEST: string = "ADD_RECENT_TRACK_REQUEST";
export const ADD_RECENT_TRACK_SUCCESS: string = "ADD_RECENT_TRACK_SUCCESS";
export const ADD_RECENT_TRACK_FAILURE: string = "ADD_RECENT_TRACK_FAILURE";
export const CHANGE_FAVORITE_TRACK_REQUEST: string = "CHANGE_FAVORITE_TRACK_REQUEST";
export const CHANGE_FAVORITE_TRACK_SUCCESS: string = "CHANGE_FAVORITE_TRACK_SUCCESS";
export const CHANGE_FAVORITE_TRACK_FAILURE: string = "CHANGE_FAVORITE_TRACK_FAILURE";
export const GET_FAVORITE_TRACK_REQUEST: string = "GET_FAVORITE_TRACK_REQUEST";
export const GET_FAVORITE_TRACK_SUCCESS: string = "GET_FAVORITE_TRACK_SUCCESS";
export const GET_FAVORITE_TRACK_FAILURE: string = "GET_FAVORITE_TRACK_FAILURE";
export const GET_MOST_PLAYED_TRACKS_REQUEST: string = "GET_MOST_PLAYED_TRACKS_REQUEST";
export const GET_MOST_PLAYED_TRACKS_SUCCESS: string = "GET_MOST_PLAYED_TRACKS_SUCCESS";
export const GET_MOST_PLAYED_TRACKS_FAILURE: string = "GET_MOST_PLAYED_TRACKS_FAILURE";
export const GET_RECENT_TRACKS_REQUEST: string = "GET_RECENT_TRACKS_REQUEST";
export const GET_RECENT_TRACKS_SUCCESS: string = "GET_RECENT_TRACKS_SUCCESS";
export const GET_RECENT_TRACKS_FAILURE: string = "GET_RECENT_TRACKS_FAILURE";
export const GET_TRACKS_REQUEST: string = "GET_TRACKS_REQUEST";
export const GET_TRACKS_SUCCESS: string = "GET_TRACKS_SUCCESS";
export const GET_TRACKS_FAILURE: string = "GET_TRACKS_FAILURE";
export const INCREMENT_TRACK_PLAYS_REQUEST: string = "INCREMENT_TRACK_PLAYS_REQUEST";
export const INCREMENT_TRACK_PLAYS_SUCCESS: string = "INCREMENT_TRACK_PLAYS_SUCCESS";
export const INCREMENT_TRACK_PLAYS_FAILURE: string = "INCREMENT_TRACK_PLAYS_FAILURE";
export const RESET_TRACKS: string = "RESET_TRACKS";
export const UPDATE_TRACKS: string = 'UPDATE_TRACKS';