'use strict';

/**
 * @format
 * @flow
 */

export const NEXT_TRACK_REQUEST: string = 'NEXT_TRACK_REQUEST';
export const NEXT_TRACK_SUCCESS: string = 'NEXT_TRACK_SUCCESS';
export const NEXT_TRACK_FAILURE: string = 'NEXT_TRACK_FAILURE';
export const PAUSE_PLAYER_REQUEST: string = 'PAUSE_PLAYER_REQUEST';
export const PAUSE_PLAYER_SUCCESS: string = 'PAUSE_PLAYER_SUCCESS';
export const PAUSE_PLAYER_FAILURE: string = 'PAUSE_PLAYER_FAILURE';
export const PLAY_TRACK_REQUEST: string = 'PLAY_TRACK_REQUEST';
export const PLAY_TRACK_SUCCESS: string = 'PLAY_TRACK_SUCCESS';
export const PLAY_TRACK_FAILURE: string = 'PLAY_TRACK_FAILURE';
export const PREVIOUS_TRACK_REQUEST: string = 'PREVIOUS_TRACK_REQUEST';
export const PREVIOUS_TRACK_SUCCESS: string = 'PREVIOUS_TRACK_SUCCESS';
export const PREVIOUS_TRACK_FAILURE: string = 'PREVIOUS_TRACK_FAILURE';
export const RESET_PLAYER: string = 'RESET_PLAYER';
export const SEEK_POSITION_REQUEST: string = 'SEEK_POSITION_REQUEST';
export const SEEK_POSITION_SUCCESS: string = 'SEEK_POSITION_SUCCESS';
export const SEEK_POSITION_FAILURE: string = 'SEEK_POSITION_FAILURE';
export const START_PLAYER_REQUEST: string = 'START_PLAYER_REQUEST';
export const START_PLAYER_SUCCESS: string = 'START_PLAYER_SUCCESS';
export const START_PLAYER_FAILURE: string = 'START_PLAYER_FAILURE';
export const STOP_PLAYER_REQUEST: string = 'STOP_PLAYER_REQUEST';
export const STOP_PLAYER_SUCCESS: string = 'STOP_PLAYER_SUCCESS';
export const STOP_PLAYER_FAILURE: string = 'STOP_PLAYER_FAILURE';
export const TOGGLE_MUTE_REQUEST: string = 'TOGGLE_MUTE_REQUEST';
export const TOGGLE_MUTE_SUCCESS: string = 'TOGGLE_MUTE_SUCCESS';
export const TOGGLE_MUTE_FAILURE: string = 'TOGGLE_MUTE_FAILURE';
export const TOGGLE_PAUSE_REQUEST: string = 'TOGGLE_PAUSE_REQUEST';
export const TOGGLE_PAUSE_SUCCESS: string = 'TOGGLE_PAUSE_SUCCESS';
export const TOGGLE_PAUSE_FAILURE: string = 'TOGGLE_PAUSE_FAILURE';
export const TOGGLE_REPEAT_REQUEST: string = 'TOGGLE_REPEAT_REQUEST';
export const TOGGLE_REPEAT_SUCCESS: string = 'TOGGLE_REPEAT_SUCCESS';
export const TOGGLE_REPEAT_FAILURE: string = 'TOGGLE_REPEAT_FAILURE';
export const TOGGLE_SHUFFLE_REQUEST: string = 'TOGGLE_SHUFFLE_REQUEST';
export const TOGGLE_SHUFFLE_SUCCESS: string = 'TOGGLE_SHUFFLE_SUCCESS';
export const TOGGLE_SHUFFLE_FAILURE: string = 'TOGGLE_SHUFFLE_FAILURE';
export const UPDATE_PLAYER: string = 'UPDATE_PLAYER';