'use strict';

/**
 * @format
 * @flow
 */

export const CHANGE_COVER_PHOTO_REQUEST: string = 'CHANGE_COVER_PHOTO_REQUEST';
export const CHANGE_COVER_PHOTO_SUCCESS: string = 'CHANGE_COVER_PHOTO_SUCCESS';
export const CHANGE_COVER_PHOTO_FAILURE: string = 'CHANGE_COVER_PHOTO_FAILURE';
export const CHANGE_PROFILE_PHOTO_REQUEST: string = 'CHANGE_PROFILE_PHOTO_REQUEST';
export const CHANGE_PROFILE_PHOTO_SUCCESS: string = 'CHANGE_PROFILE_PHOTO_SUCCESS';
export const CHANGE_PROFILE_PHOTO_FAILURE: string = 'CHANGE_PROFILE_PHOTO_FAILURE';
export const GET_USER_IMAGE_REQUEST: string = 'GET_USER_IMAGE_REQUEST';
export const GET_USER_IMAGE_SUCCESS: string = 'GET_USER_IMAGE_SUCCESS';
export const GET_USER_IMAGE_FAILURE: string = 'GET_USER_IMAGE_FAILURE';
export const RESET_USERS: string = 'RESET_USERS';
export const SAVE_PROFILE_REQUEST: string = 'SAVE_PROFILE_REQUEST';
export const SAVE_PROFILE_SUCCESS: string = 'SAVE_PROFILE_SUCCESS';
export const SAVE_PROFILE_FAILURE: string = 'SAVE_PROFILE_FAILURE';
export const UPDATE_USERS: string = 'UPDATE_USERS';