'use strict';

/**
 * @format
 * @flow
 */

export const ADD_CURRENT_USER: string = 'ADD_CURRENT_USER';
export const ADD_FAVORITE_TRACK: string = 'ADD_FAVORITE_TRACK';
export const ADD_FRIEND_LIVE_NOTIFICATION_REQUEST: string = 'ADD_FRIEND_LIVE_NOTIFICATION_REQUEST';
export const ADD_FRIEND_LIVE_NOTIFICATION_SUCCESS: string = 'ADD_FRIEND_LIVE_NOTIFICATION_SUCCESS';
export const ADD_FRIEND_LIVE_NOTIFICATION_FAILURE: string = 'ADD_FRIEND_LIVE_NOTIFICATION_FAILURE';
export const ADD_USERS: string = 'ADD_USERS';
export const ADD_USER_MOST_PLAYED: string = 'ADD_USER_MOST_PLAYED';
export const ADD_USER_RECENTLY_PLAYED: string = 'ADD_USER_RECENTLY_PLAYED';
export const ADD_USER_RECENT_TRACK: string = 'ADD_USER_RECENT_TRACK';
export const ADD_USER_TOP_PLAYLISTS: string = 'ADD_USER_TOP_PLAYLISTS';
export const BLOCK_USER_REQUEST: string = 'BLOCK_USER_REQUEST';
export const BLOCK_USER_SUCCESS: string = 'BLOCK_USER_SUCCESS';
export const BLOCK_USER_FAILURE: string = 'BLOCK_USER_FAILURE';
export const CHANGE_COVER_PHOTO_REQUEST: string = 'CHANGE_COVER_PHOTO_REQUEST';
export const CHANGE_COVER_PHOTO_SUCCESS: string = 'CHANGE_COVER_PHOTO_SUCCESS';
export const CHANGE_COVER_PHOTO_FAILURE: string = 'CHANGE_COVER_PHOTO_FAILURE';
export const CHANGE_PROFILE_PHOTO_REQUEST: string = 'CHANGE_PROFILE_PHOTO_REQUEST';
export const CHANGE_PROFILE_PHOTO_SUCCESS: string = 'CHANGE_PROFILE_PHOTO_SUCCESS';
export const CHANGE_PROFILE_PHOTO_FAILURE: string = 'CHANGE_PROFILE_PHOTO_FAILURE';
export const GET_USER_IMAGE_REQUEST: string = 'GET_USER_IMAGE_REQUEST';
export const GET_USER_IMAGE_SUCCESS: string = 'GET_USER_IMAGE_SUCCESS';
export const GET_USER_IMAGE_FAILURE: string = 'GET_USER_IMAGE_FAILURE';
export const CLEAR_CAMERA_ROLL_PHOTOS: string = 'CLEAR_CAMERA_ROLL_PHOTOS';
export const FOLLOW_USER_REQUEST: string = 'FOLLOW_USER_REQUEST';
export const FOLLOW_USER_SUCCESS: string = 'FOLLOW_USER_SUCCESS';
export const FOLLOW_USER_FAILURE: string = 'FOLLOW_USER_FAILURE';
export const REMOVE_FRIEND_LIVE_NOTIFICATION_REQUEST: string = 'REMOVE_FRIEND_LIVE_NOTIFICATION_REQUEST';
export const REMOVE_FRIEND_LIVE_NOTIFICATION_SUCCESS: string = 'REMOVE_FRIEND_LIVE_NOTIFICATION_SUCCESS';
export const REMOVE_FRIEND_LIVE_NOTIFICATION_FAILURE: string = 'REMOVE_FRIEND_LIVE_NOTIFICATION_FAILURE';
export const RESET_USERS: string = 'RESET_USERS';
export const SAVE_PROFILE_REQUEST: string = 'SAVE_PROFILE_REQUEST';
export const SAVE_PROFILE_SUCCESS: string = 'SAVE_PROFILE_SUCCESS';
export const SAVE_PROFILE_FAILURE: string = 'SAVE_PROFILE_FAILURE';
export const SEARCH_USERS_REQUEST: string = 'SEARCH_USERS_REQUEST';
export const SEARCH_USERS_SUCCESS: string = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS_FAILURE: string = 'SEARCH_USERS_FAILURE';
export const SET_CAMERA_ROLL_PHOTO_INDEX: string = 'SET_CAMERA_ROLL_PHOTO_INDEX';
export const UNBLOCK_USER_REQUEST: string = 'UNBLOCK_USER_REQUEST';
export const UNBLOCK_USER_SUCCESS: string = 'UNBLOCK_USER_SUCCESS';
export const UNBLOCK_USER_FAILURE: string = 'UNBLOCK_USER_FAILURE';
export const UNFOLLOW_USER_REQUEST: string = 'UNFOLLOW_USER_REQUEST';
export const UNFOLLOW_USER_SUCCESS: string = 'UNFOLLOW_USER_SUCCESS';
export const UNFOLLOW_USER_FAILURE: string = 'UNFOLLOW_USER_FAILURE';
export const UPDATE_USERS: string = 'UPDATE_USERS';