'use strict';

/**
 * @format
 * @flow
 */

export const GET_PLAYLISTS_REQUEST: string = 'GET_PLAYLISTS_REQUEST';
export const GET_PLAYLISTS_SUCCESS: string = 'GET_PLAYLISTS_SUCCESS';
export const GET_PLAYLISTS_FAILURE: string = 'GET_PLAYLISTS_FAILURE';
export const GET_PLAYLIST_TOP_MEMBERS_REQUEST: string = 'GET_PLAYLIST_TOP_MEMBERS_REQUEST';
export const GET_PLAYLIST_TOP_MEMBERS_SUCCESS: string = 'GET_PLAYLIST_TOP_MEMBERS_SUCCESS';
export const GET_PLAYLIST_TOP_MEMBERS_FAILURE: string = 'GET_PLAYLIST_TOP_MEMBERS_FAILURE';
export const GET_TOP_PLAYLISTS_REQUEST: string = 'GET_TOP_PLAYLISTS_REQUEST';
export const GET_TOP_PLAYLISTS_SUCCESS: string = 'GET_TOP_PLAYLISTS_SUCCESS';
export const GET_TOP_PLAYLISTS_FAILURE: string = 'GET_TOP_PLAYLISTS_FAILURE';
export const GET_PLAYLIST_TOP_TRACKS_REQUEST: string = 'GET_PLAYLIST_TOP_TRACKS_REQUEST';
export const GET_PLAYLIST_TOP_TRACKS_SUCCESS: string = 'GET_PLAYLIST_TOP_TRACKS_SUCCESS';
export const GET_PLAYLIST_TOP_TRACKS_FAILURE: string = 'GET_PLAYLIST_TOP_TRACKS_FAILURE';
export const GET_PLAYLIST_TRACKS_REQUEST: string = 'GET_PLAYLIST_TRACKS_REQUEST';
export const GET_PLAYLIST_TRACKS_SUCCESS: string = 'GET_PLAYLIST_TRACKS_SUCCESS';
export const GET_PLAYLIST_TRACKS_FAILURE: string = 'GET_PLAYLIST_TRACKS_FAILURE';
export const INCREMENT_PLAYLIST_PLAYS_REQUEST: string = 'INCREMENT_PLAYLIST_PLAYS_REQUEST';
export const INCREMENT_PLAYLIST_PLAYS_SUCCESS: string = 'INCREMENT_PLAYLIST_PLAYS_SUCCESS';
export const INCREMENT_PLAYLIST_PLAYS_FAILURE: string = 'INCREMENT_PLAYLIST_PLAYS_FAILURE';
export const RESET_PLAYLISTS: string = 'RESET_PLAYLISTS';
export const UPDATE_PLAYLISTS: string = 'UPDATE_PLAYLISTS';