"use strict";

/**
 * @format
 * @flow
 */

export const GET_ARTIST_IMAGES_REQUEST: string = 'GET_ARTIST_IMAGES_REQUEST';
export const GET_ARTIST_IMAGES_SUCCESS: string = 'GET_ARTIST_IMAGES_SUCCESS';
export const GET_ARTIST_IMAGES_FAILURE: string = 'GET_ARTIST_IMAGES_FAILURE';
export const GET_ARTISTS_REQUEST: string = 'GET_ARTISTS_REQUEST';
export const GET_ARTISTS_SUCCESS: string = 'GET_ARTISTS_SUCCESS';
export const GET_ARTISTS_FAILURE: string = 'GET_ARTISTS_FAILURE';
export const GET_ARTIST_TOP_ALBUMS_REQUEST: string = 'GET_ARTIST_TOP_ALBUMS_REQUEST';
export const GET_ARTIST_TOP_ALBUMS_SUCCESS: string = 'GET_ARTIST_TOP_ALBUMS_SUCCESS';
export const GET_ARTIST_TOP_ALBUMS_FAILURE: string = 'GET_ARTIST_TOP_ALBUMS_FAILURE';
export const GET_ARTIST_TOP_LISTENERS_REQUEST: string = 'GET_ARTIST_TOP_LISTENERS_REQUEST';
export const GET_ARTIST_TOP_LISTENERS_SUCCESS: string = 'GET_ARTIST_TOP_LISTENERS_SUCCESS';
export const GET_ARTIST_TOP_LISTENERS_FAILURE: string = 'GET_ARTIST_TOP_LISTENERS_FAILURE';
export const GET_ARTIST_TOP_PLAYLISTS_REQUEST: string = 'GET_ARTIST_TOP_PLAYLISTS_REQUEST';
export const GET_ARTIST_TOP_PLAYLISTS_SUCCESS: string = 'GET_ARTIST_TOP_PLAYLISTS_SUCCESS';
export const GET_ARTIST_TOP_PLAYLISTS_FAILURE: string = 'GET_ARTIST_TOP_PLAYLISTS_FAILURE';
export const GET_ARTIST_TOP_TRACKS_REQUEST: string = 'GET_ARTIST_TOP_TRACKS_REQUEST';
export const GET_ARTIST_TOP_TRACKS_SUCCESS: string = 'GET_ARTIST_TOP_TRACKS_SUCCESS';
export const GET_ARTIST_TOP_TRACKS_FAILURE: string = 'GET_ARTIST_TOP_TRACKS_FAILURE';
export const INCREMENT_ARTIST_PLAYS_REQUEST: string = 'INCREMENT_ARTIST_PLAYS_REQUEST';
export const INCREMENT_ARTIST_PLAYS_SUCCESS: string = 'INCREMENT_ARTIST_PLAYS_SUCCESS';
export const INCREMENT_ARTIST_PLAYS_FAILURE: string = 'INCREMENT_ARTIST_PLAYS_FAILURE';
export const RESET_ARTISTS: string = 'RESET_ARTISTS';
export const UPDATE_ARTISTS: string = 'UPDATE_ARTISTS';