'use strict';

/**
 * @format
 * @flow
 */

import React from 'react';
import {StyleSheet} from 'react-native';
import {
  type ViewStyleProp,
  type TextStyleProp,
  type ImageStyleProp,
} from 'react-native/Libraries/StyleSheet/StyleSheet';

interface Styles {
  container: ViewStyleProp,
  scrollContainer: ViewStyleProp,
  scrollWrap: ViewStyleProp,
  section: ViewStyleProp,
  sectionTitle: TextStyleProp,
  playlistCreatorSpotify: ViewStyleProp,
  playlistCreator: ViewStyleProp,
  playlistCreatorSpotifyImage: TextStyleProp,
  playlistCreatorImage: ImageStyleProp | ViewStyleProp,
  default: ViewStyleProp,
  defaultImage: ImageStyleProp,
  playlistCreatorName: TextStyleProp,
  arrowForward: TextStyleProp,
  playlistMember: ViewStyleProp,
  playlistMemberImage: ImageStyleProp,
  playlistMemberName: TextStyleProp,
  playlistMemberViewAllFilter: ViewStyleProp,
  playlistMemberViewAllImage: ImageStyleProp,
  memberCountText: TextStyleProp,
  plus: TextStyleProp,
  playlistMemberAction: ViewStyleProp,
  playlistMemberImagePlaceholder: ViewStyleProp,
  playlistMemberInviteText: TextStyleProp,
  topMembersError: ViewStyleProp,
  topMembersErrorText: TextStyleProp,
  topMembersEmpty: ViewStyleProp,
  topMembersEmptyText: TextStyleProp,
  loadingSection: ViewStyleProp,
  playlistPlays: TextStyleProp,
  playlistPlaysNumber: TextStyleProp,
  topTracksError: ViewStyleProp,
  topTracksErrorText: TextStyleProp,
  topTracksEmpty: ViewStyleProp,
  topTracksEmptyText: TextStyleProp,
  header: ViewStyleProp,
  headerBackground: ViewStyleProp | ImageStyleProp,
  headerFilter: ViewStyleProp,
  nav: ViewStyleProp,
  leftIcon: TextStyleProp,
  title: TextStyleProp,
  rightIcon: ViewStyleProp,
};

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  scrollContainer: {
    flex: 1,
    backgroundColor: '#1b1b1e',
  },
  scrollWrap: {
    marginTop: 105,
    paddingBottom: 20,
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    color: '#888',
    fontSize: 16,
    fontFamily: 'Muli',
    fontWeight: '800',
    lineHeight: 20.8,
    textAlign: 'center',
    backgroundColor: 'transparent',
  },
  playlistCreatorSpotify: {
    paddingHorizontal: 20,
    paddingVertical: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  playlistCreator: {
    paddingHorizontal: 20,
    paddingVertical: 15,
    flexDirection: 'row',
    height: 82,
    alignItems: 'center',
  },
  playlistCreatorSpotifyImage: {
    width: 60,
    height: 60,
    fontSize: 60,
    marginRight: 10,
    borderRadius: 30,
  },
  playlistCreatorImage: {
    width: 60,
    height: 60,
    marginRight: 10,
    borderRadius: 30,
  },
  default: {
    height: 60,
    width: 60,
    backgroundColor: '#323232',
    marginRight: 10,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  defaultImage: {
    flex: 1,
    height: 37.19,
    width: 45,
  },
  playlistCreatorName: {
    flex: 6,
    color: '#fefefe',
    fontSize: 18,
    fontWeight: '600',
    fontFamily: 'Muli',
    lineHeight: 18,
  },
  arrowForward: {
    flex: 1,
    textAlign: 'right',
    fontSize: 35,
    alignSelf: 'center',
  },
  playlistMember: {
    width: 80,
    height: 90,
    marginVertical: 20,
    marginRight: 20,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  playlistMemberImage: {
    width: 60,
    height: 60,
    borderRadius: 30,
  },
  playlistMemberName: {
    color: '#fefefe',
    fontSize: 20,
    fontFamily: 'Muli',
    fontWeight: '600',
    lineHeight: 26,
  },
  playlistMemberViewAllFilter: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#888',
    opacity: 0.5,
    position: 'absolute',
    zIndex: -1,
  },
  playlistMemberViewAllImage: {
    width: 60,
    height: 60,
    borderRadius: 30,
    position: 'absolute',
    zIndex: -2,
  },
  memberCountText: {
    color: '#fefefe',
    fontSize: 20,
    fontFamily: 'Muli',
    fontWeight: '600',
    lineHeight: 26,
    backgroundColor: 'transparent',
    marginTop: 17,
  },
  plus: {
    textAlign: 'center',
    paddingTop: 4,
    fontSize: 40,
  },
  playlistMemberAction: {
    width: 80,
    height: 90,
    marginVertical: 20,
    marginHorizontal: 20,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  playlistMemberImagePlaceholder: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#888',
    justifyContent: 'center',
    alignItems: 'center',
  },
  playlistMemberInviteText: {
    color: '#fefefe',
    fontSize: 20,
    fontFamily: 'Muli',
    fontWeight: '600',
    lineHeight: 26,
  },
  topMembersError: {
    height: 80,
    marginVertical: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  topMembersErrorText: {
    color: '#fefefe',
    fontSize: 18,
    fontFamily: 'Muli',
    fontWeight: '600',
    lineHeight: 23.4,
  },
  topMembersEmpty: {
    height: 80,
    marginVertical: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  topMembersEmptyText: {
    color: '#fefefe',
    fontSize: 18,
    fontFamily: 'Muli',
    fontWeight: '600',
    lineHeight: 23.4,
  },
  loadingSection: {
    flexDirection: 'row',
  },
  playlistPlays: {
    marginTop: 30,
    marginBottom: 20,
    color: '#888',
    fontSize: 16,
    fontWeight: '800',
    fontFamily: 'Muli',
    textAlign: 'center',
    lineHeight: 39,
    backgroundColor: 'transparent',
  },
  playlistPlaysNumber: {
    color: '#fefefe',
    fontSize: 30,
  },
  topTracksError: {
    height: 72,
    justifyContent: 'center',
    alignItems: 'center',
  },
  topTracksErrorText: {
    color: '#fefefe',
    fontSize: 20,
    fontWeight: '600',
    fontFamily: 'Muli',
    lineHeight: 26,
  },
  topTracksEmpty: {
    height: 72,
    justifyContent: 'center',
    alignItems: 'center',
  },
  topTracksEmptyText: {
    color: '#fefefe',
    fontSize: 20,
    fontWeight: '600',
    fontFamily: 'Muli',
    lineHeight: 26,
  },
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 70,
    paddingTop: 10,
    paddingHorizontal: 20,
    backgroundColor: '#1b1b1e',
    shadowColor: '#101010',
    shadowOffset: {width: 0, height: 0},
    shadowRadius: 5,
    shadowOpacity: 0.9,
  },
  headerBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: null,
  },
  headerFilter: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(27,27,30,0.5)',
  },
  nav: {
    height: 70,
    flexDirection: 'row',
    alignItems: 'center',
  },
  leftIcon: {
    flex: 1,
    height: 35,
    fontSize: 35,
    backgroundColor: 'transparent',
    alignSelf: 'center',
  },
  title: {
    flex: 6,
    color: '#fefefe',
    fontSize: 24,
    fontFamily: 'Muli',
    fontWeight: '800',
    lineHeight: 28.8,
    textAlign: 'center',
    alignSelf: 'center',
    backgroundColor: 'transparent',
  },
  rightIcon: {
    flex: 1,
    height: 35,
    textAlign: 'right',
    backgroundColor: 'transparent',
  },
});